# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values
steps:
  - id: build
    name: docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - $_IMAGE_NAME
      - .

  - id: push
    name: docker
    args:
      - push
      - $_IMAGE_NAME

  - id: deploy
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - "--image=$_IMAGE_NAME"
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
      - "--allow-unauthenticated"

images:
  - $_IMAGE_NAME
