steps:
  - id: build
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --context=dir://.
      - --destination=$_IMAGE_NAME
      - --no-push=false
      - --cache=true

  - id: deploy
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - "--image=$_IMAGE_NAME"
      - "--region=$_DEPLOY_REGION"
      - "--quiet"

images:
  - $_IMAGE_NAME
